### ISSUE TITLE
Introduction to Operating Systems

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#1]
[Introduction to Operating Systems](https://core.ewha.ac.kr/publicview/C0101020140307151724641842?vmode=f)
2022년 7월 12일 (화) 20시까지

**Comment by Jineh** [comment]
https://www.notion.so/ch1-6234f2f78db24a6b967d388fa5335b51

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch1-cddb5ba577064bccbc3a22072e974236
