### ISSUE TITLE
Virtual Memory

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#10]
[Virtual Memory1](https://core.ewha.ac.kr/publicview/C0101020140509151648408460?vmode=f)
[Virtual Memory2](https://core.ewha.ac.kr/publicview/C0101020140513133424380501?vmode=f)
2022년 8월 23일 (화) 20시까지

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch9-0cbdfbdcd9174afb86fba74656f23770

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch9-55813d36e4da4a529ff27501f19bc077
