### ISSUE TITLE
Disk Management and Scheduling

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#12]
[Disk Management and Scheduling1](https://core.ewha.ac.kr/publicview/C0101020140523151255773807?vmode=f)
[Disk Management and Scheduling2](https://core.ewha.ac.kr/publicview/C0101020140527124647396004?vmode=f)
2022년 9월 6일 (화) 20시까지

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch11-fc685bdd279a4d10a70c7c761e3830a7

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch11-Disk-Management-and-Scheduling-23fb5ea99aa147ecabb9d2cfe3d6712f
