### ISSUE TITLE
System Structure & Program Execution

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#2]
[System Structure & Program Execution1](https://core.ewha.ac.kr/publicview/C0101020140311132925816476?vmode=f)
[System Structure & Program Execution2](https://core.ewha.ac.kr/publicview/C0101020140314151238067290?vmode=f)
2022년 7월 15일 (금) 20시까지

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch2-08e5ffd12a274ae3a89b07e407abf394

**Comment by dudtjs1021ej** [comment]
문제지
https://lyrical-bicycle-d28.notion.site/ch2-9f281488b0c44d8b84b28cdf1eba9ca9

**Comment by dudtjs1021ej** [comment]
> https://lyrical-bicycle-d28.notion.site/ch2-9f281488b0c44d8b84b28cdf1eba9ca9

답지
https://lyrical-bicycle-d28.notion.site/3497022ea880463e9aa02235d533209c
