### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#3]
[Process1](https://core.ewha.ac.kr/publicview/C0101020140318134023355997?vmode=f)
[Process2](https://core.ewha.ac.kr/publicview/C0101020140321141759959993?vmode=f)
[Process3](https://core.ewha.ac.kr/publicview/C0101020140321143516139010?vmode=f)
2022년 7월 19일 (화) 20시까지

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch3-5d893bd4cdb74cce95f2377eaa0a2ebe

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch3-ee1a729e40214b3bbb2f641349a4a394
