### ISSUE TITLE
Process Management

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#4]
[Process Management 1](https://core.ewha.ac.kr/publicview/C0101020140321144554159683?vmode=f)
[Process Management 2](https://core.ewha.ac.kr/publicview/C0101020140325134428879622?vmode=f)
2022년 7월 22일 (금) 20시까지

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch4-d39db70fb4fc42eda2ff56283fd736b1

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch4-e65d2d85e9384c1aa85a0ea0bec2a0dc
