### ISSUE TITLE
CPU Scheduling

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#5]
[CPU Scheduling1](https://core.ewha.ac.kr/publicview/C0101020140328151311578473?vmode=f])
[CPU Scheduling2](https://core.ewha.ac.kr/publicview/C0101020140401134252676046?vmode=f])
2022년 7월 26일 (화) 20시까지

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch5-CPU-7876c279bf144a2a959af2bba992afa9

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch5-ed9d862d3a40425d875272f0ee851a2f
