### ISSUE TITLE
Process Synchronization

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#6]
[Process Synchronization1](https://core.ewha.ac.kr/publicview/C0101020140404144354492628?vmode=f)
[Process Synchronization2](https://core.ewha.ac.kr/publicview/C0101020140404151340260748?vmode=f)
[Process Synchronization3](https://core.ewha.ac.kr/publicview/C0101020140408134626290222?vmode=f)
2022 7월 29일 (금) 20시까지

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch6-dfaf83b212964dc1aae2b5671899e8b3

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch6-bc2d506a3e77441582207edb676accab
