### ISSUE TITLE
운영체제 중간테스트

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#7]
2022년 8월 6일 (토) 22시
각 단원 2문제씩 총 12문제 풀이

**Comment by dudtjs1021ej** [comment]
문제지
https://lyrical-bicycle-d28.notion.site/7c35d524d2b449e6bec054c12d90a3f6

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/2354439b07174fbfa834581c7f4bcd9e
