### ISSUE TITLE
Deadlocks

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#8]
[Deadlocks1](https://core.ewha.ac.kr/publicview/C0101020140411151510275738?vmode=f)
[Deadlocks2](https://core.ewha.ac.kr/publicview/C0101020140415131030840772?vmode=f)
2022년 8월 9일 (화) 20시까지

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/ch7-9b47b85136d547deb73e8fb7cfe95c8d

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch7-195f8d605f2841d8a39cc7fad2d8efae
