### ISSUE TITLE
Memory Management1

### ISSUE THREAD

**Issue by dudtjs1021ej** [dudtjs1021ej/CS_study#9]
[Memory Management1](https://core.ewha.ac.kr/publicview/C0101020140425151219100144?vmode=f)
[Memory Management2](https://core.ewha.ac.kr/publicview/C0101020140429132440045277?vmode=f)
2022년 8월 16일 (화) 20시까지

**Comment by dudtjs1021ej** [comment]
https://lyrical-bicycle-d28.notion.site/7a2dc4576a414522a617bb6a3c10597d

**Comment by Jineh** [comment]
https://root-direction-713.notion.site/ch8-c3a01c72fee94636825e90cb4d62e239
